name: Project Kathani Daily Pulse

on:
  schedule:
    - cron: '0 5 * * *' # 5 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Kathani Engine
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python scripts/generate_story.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Kathani-Bot"
          git config --global user.email "bot@kathani.com"
          git add .
          git commit -m "Archive: Story for $(date +'%Y-%m-%d')"
          git push
